name: Build Syncthing

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  GO_VERSION: "~1.23.0"

jobs:
  package-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: go build ./cmd/sbom2tree -o sbom2tree
      - name: Archive
        run: tar -czf sbom2tree-macos-arm64.tar.gz sbom2tree
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: packages-macos
          path: sbom2tree-macos-arm64.tar.gz
